import type { FeatureCard, Theme, PainPoint } from './types';

export interface ExportContext {
  cards: FeatureCard[];
  themes: Theme[];
  painPoints: PainPoint[];
  generatedAt: Date;
  mode: 'live' | 'demo';
}

export function toMarkdown(ctx: ExportContext): string {
  const accepted = ctx.cards
    .filter((c) => c.status === 'accepted' || c.status === 'edited')
    .sort((a, b) => b.priority_score - a.priority_score);

  const ts = ctx.generatedAt.toISOString();
  const modeLabel = ctx.mode === 'live' ? 'Live (Anthropic Claude)' : 'Demo Mode';

  const lines: string[] = [];
  lines.push('# Product Requirements Document');
  lines.push('');
  lines.push(`_Generated by InsightDraft on ${ts}. Pipeline mode: ${modeLabel}._`);
  lines.push('');
  lines.push('## Executive summary');
  lines.push('');
  lines.push(`This PRD was synthesized from raw user research using a three-agent chain (Researcher → Synthesis → Strategy), then reviewed by a human PM. ${accepted.length} feature${accepted.length === 1 ? '' : 's'} accepted and ranked by priority.`);
  lines.push('');
  if (accepted.length === 0) {
    lines.push('_No feature cards were accepted in review._');
    return lines.join('\n');
  }

  lines.push('## Prioritized features');
  lines.push('');
  accepted.forEach((c, i) => {
    lines.push(`### ${i + 1}. ${c.feature_name}`);
    lines.push('');
    lines.push(`**Priority:** ${c.priority_score}/10  |  **Confidence:** ${c.confidence_score}/100  |  **Status:** ${c.status}`);
    lines.push('');
    lines.push('**User problem**');
    lines.push('');
    lines.push(c.user_problem);
    lines.push('');
    lines.push('**Proposed solution**');
    lines.push('');
    lines.push(c.proposed_solution);
    lines.push('');
    lines.push('**Success metric**');
    lines.push('');
    lines.push(c.success_metric);
    lines.push('');
    lines.push('---');
    lines.push('');
  });

  lines.push('## Themes (Synthesis Agent)');
  lines.push('');
  ctx.themes.forEach((t) => {
    lines.push(`### ${t.theme_name}`);
    lines.push('');
    lines.push(`_Confidence: ${t.confidence_score}/100_`);
    lines.push('');
    lines.push(t.summary);
    lines.push('');
    if (t.assumptions?.length) {
      lines.push('**Assumptions to validate:**');
      t.assumptions.forEach((a) => lines.push(`- ${a}`));
      lines.push('');
    }
  });

  lines.push('## Source pain points (Researcher Agent)');
  lines.push('');
  ctx.painPoints.forEach((p) => {
    lines.push(`- **[${p.severity}]** ${p.pain_point}`);
    lines.push(`  - _Quote:_ "${p.quote}"`);
    lines.push(`  - _Frequency:_ ${p.frequency_estimate}`);
    lines.push(`  - _Confidence:_ ${p.confidence_score}/100`);
  });

  return lines.join('\n');
}

export function downloadBlob(filename: string, contents: string, mime = 'text/markdown') {
  const blob = new Blob([contents], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      const ok = document.execCommand('copy');
      document.body.removeChild(ta);
      return ok;
    } catch {
      return false;
    }
  }
}
